influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
  volumes:
    - ./influxdb/data:/var/lib/influxdb
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - ./grafana/data:/var/lib/grafana

cryptoflux:
  image: cryptoflux
  links:
    - influxdb
  env_file:
    - cryptoflux.env
